apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-service
spec:
  selector:
    app: node-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # This should match the container's exposed port
  type: NodePort

