name: PR-EVENT-TRIGGER

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display branch name
        run: |
          echo "The pull request is from branch:${{ github.event.pull_request.head.ref }}"
          echo "The pull request base is :${{github.event.pull_request.base.ref}}"

      - name: Display ID TOCKEN
        run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN $ACTIONS_ID_TOKEN_REQUEST_URL"
          ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://demo" | jq -r .value)
          echo $ID_TOKEN
          echo $ID_TOKEN | base64
