# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python update AWS secret value workflow
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        description: 'Name of secret'
        required: true
        type: choice
        options:
        - test-secret-managed
        - test-secret-managed-2
      REGION_NAME:
        description: 'Region code'
        default: 'ap-northeast-1'
        required: true
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run python script
        env:
          SECRET_NAME: ${{ inputs.SECRET_NAME }}
          REGION_NAME: ${{ inputs.REGION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MINT_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINT_AWS_SECRET_ACCESS_KEY }}
          SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
          TEST_SECRET_VALUE: ${{ secrets.TEST_SECRET_VALUE }}

        run: python PutSecret-value.py
