name: Test environment secrets

on: [workflow_dispatch]

env:
  environment: "staging"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Replace properties file
      run: echo "${{secrets.TEST_ENV_SECRET}}" > secret_value

    - name: Display secret file content
      run: ls && cat secret_value
