name: Write Secret to File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Write secret to file
      run: echo "${{ secrets.MINT_AWS_ACCESS_KEY_ID }}" > my_secret_file.txt

    - name: Display secret file content
      run: cat my_secret_file.txt
