name: Write Secret to File

on: [workflow_dispatch]

env:
  PROPERTIES_FILE: "STG_STREAM_PROPERTIES" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: print variable value
      run: echo ${{${GITHUB_RUN_ATTEMPT}}
      
    #- name: Write secret to file
     # run: echo "${{ secrets.MINT_AWS_ACCESS_KEY_ID }}" > my_secret_file.txt
     
    - name: 04.Replace properties file
      run: echo "${{secrets[env.PROPERTIES_FILE] }}" > my_stream.properties

    - name: Display secret file content
      run: cat my_stream.properties
