name: Test environment secrets

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Write content to file
      run: echo "${{secrets.TEST_ENV_SECRET}}" > secret_value

    - name: Display secret file content
      run: cat secret_value
